export enum MOOD_TYPE {
  HAPPY = 'HAPPY',
  NEUTRAL = 'NEUTRAL',
  SAD = 'SAD',
  STRESS = 'STRESS',
}

export enum TEXT_VARIANT {
  HEADER_TITLE = 'HEADER_TITLE',
  TITLE = 'TITLE',
  SUBTITLE = 'SUBTITLE',
  REGULAR = 'REGULAR',
}
